export const MCP_OAUTH_AUTHORIZATION_STATUS_AUTHORIZED = "authorized";
export const MCP_OAUTH_AUTHORIZATION_STATUS_REDIRECT = "redirect";
export const MCP_OAUTH_AUTHORIZATION_STATUS_MANUAL_CLIENT_REGISTRATION_REQUIRED =
  "manual_client_registration_required";

export const MCP_OAUTH_AUTHORIZATION_STATUS_VALUES = [
  MCP_OAUTH_AUTHORIZATION_STATUS_AUTHORIZED,
  MCP_OAUTH_AUTHORIZATION_STATUS_REDIRECT,
  MCP_OAUTH_AUTHORIZATION_STATUS_MANUAL_CLIENT_REGISTRATION_REQUIRED,
] as const;

export type McpOAuthAuthorizationStatus =
  (typeof MCP_OAUTH_AUTHORIZATION_STATUS_VALUES)[number];

export const MCP_OAUTH_MANUAL_CLIENT_REGISTRATION_REASON_DCR_FAILED =
  "dcr_failed";
export const MCP_OAUTH_MANUAL_CLIENT_REGISTRATION_REASON_REGISTRATION_NOT_AVAILABLE =
  "registration_not_available";

export const MCP_OAUTH_MANUAL_CLIENT_REGISTRATION_REASON_VALUES = [
  MCP_OAUTH_MANUAL_CLIENT_REGISTRATION_REASON_DCR_FAILED,
  MCP_OAUTH_MANUAL_CLIENT_REGISTRATION_REASON_REGISTRATION_NOT_AVAILABLE,
] as const;

export type McpOAuthManualClientRegistrationReason =
  (typeof MCP_OAUTH_MANUAL_CLIENT_REGISTRATION_REASON_VALUES)[number];
