# yaml-language-server: $schema=http://json.schemastore.org/github-action.json

name: "Validate docs.tambo.co links"
description: Validate docs.tambo.co URLs referenced in the repo against the docs MDX file structure.

runs:
  using: "composite"
  steps:
    - name: Validate docs.tambo.co links
      shell: bash
      run: bash "${{ github.action_path }}/validate-docs-links.sh"
