import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { sentientLight } from "@/lib/fonts";
import { cn } from "@/lib/utils";
import "./globals.css";
import Providers from "@/components/authentication/providers";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/auth";
import ClientLayout from "@/components/tamboAuthentication/client-layout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body
        className={cn(
          `${geistSans.variable} ${geistMono.variable} ${sentientLight.variable} antialiased`,
        )}
      >
        <Providers>
          <ClientLayout userToken={session?.accessToken}>
            {children}
          </ClientLayout>
        </Providers>
      </body>
    </html>
  );
}
