name: Release and Publish NPM

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          manifest-file: .release-please-manifest.json

      # Only checkout and build if we're publishing to npm
      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.react-sdk--release_created || steps.release.outputs.cli--release_created || steps.release.outputs.create-tambo-app--release_created }}
        with:
          fetch-depth: 0
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}

      - uses: actions/setup-node@v4
        if: ${{ steps.release.outputs.react-sdk--release_created || steps.release.outputs.cli--release_created || steps.release.outputs.create-tambo-app--release_created }}
        with:
          node-version: "22"
          cache: "npm"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        if: ${{ steps.release.outputs.react-sdk--release_created || steps.release.outputs.cli--release_created || steps.release.outputs.create-tambo-app--release_created }}
        run: npm install

      - name: Build
        if: ${{ steps.release.outputs.react-sdk--release_created || steps.release.outputs.cli--release_created || steps.release.outputs.create-tambo-app--release_created }}
        run: npm run build

      # Publish steps (only for npm packages)
      - name: Publish @tambo-ai/react to npm
        if: ${{ steps.release.outputs.react-sdk--release_created }}
        working-directory: ./react-sdk
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public

      - name: Publish tambo to npm
        if: ${{ steps.release.outputs.cli--release_created }}
        working-directory: ./cli
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public

      - name: Publish create-tambo-app to npm
        if: ${{ steps.release.outputs.create-tambo-app--release_created }}
        working-directory: ./create-tambo-app
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public
